# fly.toml app configuration file generated for jeb-blog on 2023-07-23T13:48:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jeb-blog"
primary_region = "hkg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "blog_storage"
  destination = "/Storage"