# fly.toml app configuration file generated for jeb-blog-next on 2023-12-31T13:34:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jeb-blog-next"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
